### ISSUE TITLE
Figgo crashed if there no typography or color blocks

### ISSUE THREAD

**Issue by hgenru** [B3nnyL/figgo#10]
I trying load default color palette, but the Figgo fails because of there no any typography style.
A similar error happens when no colors styles on the page. 

![image](https://user-images.githubusercontent.com/2411525/63022884-8a923200-beac-11e9-89ac-2b41c6b4f9cf.png)

The error cause on these lines
https://github.com/B3nnyL/figgo/blob/f87c1a1379ae41ea3c7219ac753dce127c605dc9/lib/service.ts#L73
https://github.com/B3nnyL/figgo/blob/f87c1a1379ae41ea3c7219ac753dce127c605dc9/lib/service.ts#L109

```
TypeError: Cannot read property 'children' of undefined
    at Object.<anonymous> (/Users/a.plesovskikh/Work/mercury-front/node_modules/figgo/dist/service.js:151:45)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/a.plesovskikh/Work/mercury-front/node_modules/figgo/dist/service.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
TypeError: Cannot read property 'children' of undefined
    at Object.<anonymous> (/Users/a.plesovskikh/Work/mercury-front/node_modules/figgo/dist/service.js:85:47)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/a.plesovskikh/Work/mercury-front/node_modules/figgo/dist/service.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
TypeError: Cannot read property 'children' of undefined
    at Object.<anonymous> (/Users/a.plesovskikh/Work/mercury-front/node_modules/figgo/dist/service.js:118:47)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/a.plesovskikh/Work/mercury-front/node_modules/figgo/dist/service.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

**Comment by B3nnyL** [comment]
Hello @hgenru, sorry for late response first. Figgo only works for templated Figma board which I showed in readme at this moment, I
